run:
  concurrency: 16
  timeout: 5m
  tests: true
  allow-parallel-runners: true

linters:
  enable-all: true
  disable:
    - gochecknoglobals
    - varnamelen
    - prealloc
    - interfacer
    - deadcode
    - varcheck
    - structcheck
    - golint
    - nosnakecase
    - exhaustivestruct
    - ifshort
    - maligned
    - scopelint
    - rowserrcheck
    - sqlclosecheck
    - structcheck
    - wastedassign
  fast: false
