run:
  concurrency: 16
  timeout: 5m
  tests: true
  allow-parallel-runners: true

linters:
  enable-all: true
  disable:
    - cyclop
    - dupword
    - gocyclo
    - gocognit
    - goerr113
    - maintidx
    - noctx
    - nlreturn
    - wsl
    - ireturn
    - contextcheck
    - gomnd
    - funlen
    - gomoddirectives
    - exhaustruct
    - funlen
    - forbidigo
    - gochecknoglobals
    - varnamelen
    - prealloc
    - interfacer
    - deadcode
    - varcheck
    - structcheck
    - exhaustivestruct
    - golint
    - nosnakecase
    - exhaustivestruct
    - ifshort
    - maligned
    - scopelint
    - rowserrcheck
    - nonamedreturns
    - tagliatelle
    - sqlclosecheck
    - structcheck
    - wastedassign
    - wrapcheck
  fast: false
